### ISSUE TITLE
source codes of projects

### ISSUE THREAD

**Issue by IpekUyguner** [acs/ghtorrent#7]
Hi, I am new to ghtorrent. I was wondering can I download the source codes from githubs with ghtorrent? Or should I use another tool (like https://github.com/src-d/borges)  to download them from the URL links?

Thanks so much!

**Comment by acs** [comment]
Ups, I can not remember pretty well, but I think that you can download directly all the GitHub events using ghtorrent. At least in 2018 when I played with this data source. Good luck @IpekUyguner !
